FROM openjdk:21-jdk

ARG SENDGRID_API_KEY
ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

WORKDIR /app
COPY target/oak-desafio-0.0.1-SNAPSHOT.jar /app/oak-desafio.jar

ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}

EXPOSE 8080
CMD ["java","-jar","oak-desafio.jar"]