version: "3.7"
services:
 # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    restart: always
    ports:
      - 5433:5432
    networks:
      - dev-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    depends_on:
      - pg-docker
    networks:
      - dev-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
# ======================================================================================================================
# APP
# ======================================================================================================================

  oak-desafio-app:
    image: fernandocanabarroahnert/oak-desafio-app
    restart: always
    build: 
      context: ../
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://pg-docker:5432/oak_desafio
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 1234567
      spring.sendgrid.api-key: ${SENDGRID_API_KEY}
    ports: 
      - 8080:8080
    depends_on:
      - pg-docker
    networks:
      - dev-network

# ======================================================================================================================
# NETWORK
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: