version: "3.7"
services:
   oak-desafio-app:
    image: fernandocanabarroahnert/oak-desafio-app
    restart: always
    build: 
      context: ../
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    ports: 
      - 8080:8080
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge