version: "3.7"
services:
 # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    restart: always
    ports:
      - 5433:5432
    networks:
      - dev-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
# ======================================================================================================================
# NETWORK
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge
volumes:
  postgres_data:
